# Generated by Django 6.0.8 on 2026-09-16 05:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_delivery_engine_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Internal/admin-facing name of the promotion.', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], db_index=True, max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value when discount_type=PERCENTAGE, otherwise fixed discount amount.', max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum total discount allowed from this promotion for a single cart/order.', max_digits=12, null=True)),
                ('minimum_cart_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Promotion applies only when the eligible cart subtotal meets or exceeds this amount.', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Master switch. Valid dates alone do not activate a promotion.')),
                ('start_at', models.DateTimeField(db_index=True, help_text='Promotion becomes eligible from this timestamp.')),
                ('end_at', models.DateTimeField(db_index=True, help_text='Promotion remains eligible until this timestamp.')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, help_text='Higher priority wins when multiple applicable promotions have the same targeting specificity.')),
                ('stackable', models.BooleanField(db_index=True, default=False, help_text='Whether this promotion may be combined with another promotion by the promotion engine.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-priority', '-created_at', '-id'),
                'indexes': [models.Index(fields=['is_active', 'start_at', 'end_at'], name='promo_active_window_idx'), models.Index(fields=['is_active', 'priority'], name='promo_active_priority_idx'), models.Index(fields=['discount_type', 'is_active'], name='promo_type_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='promo_discount_value_positive'), models.CheckConstraint(condition=models.Q(('minimum_cart_value__gte', 0)), name='promo_min_cart_value_non_negative'), models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gt', 0), _connector='OR'), name='promo_max_discount_positive_or_null'), models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENTAGE'), ('discount_value__gt', 0), ('discount_value__lte', 100)), models.Q(('discount_type', 'FIXED_AMOUNT'), ('discount_value__gt', 0)), _connector='OR'), name='promo_discount_value_matches_type')],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('ALL', 'All products'), ('CATEGORY', 'Category'), ('SUBCATEGORY', 'Subcategory'), ('BRAND', 'Brand'), ('PRODUCT', 'Product'), ('VARIANT', 'Variant')], db_index=True, max_length=20)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Brand value exactly as represented in the catalog. Used only when target_type=BRAND.', max_length=120, null=True)),
                ('brand_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='catalog.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.promotion')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='catalog.subcategory')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('promotion_id', 'target_type', 'id'),
                'indexes': [models.Index(fields=['promotion', 'target_type'], name='promo_rule_promo_type_idx'), models.Index(fields=['target_type', 'category'], name='promo_rule_category_idx'), models.Index(fields=['target_type', 'subcategory'], name='promo_rule_subcat_idx'), models.Index(fields=['target_type', 'product'], name='promo_rule_product_idx'), models.Index(fields=['target_type', 'variant'], name='promo_rule_variant_idx'), models.Index(fields=['target_type', 'brand_normalized'], name='promo_rule_brand_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('target_type', 'ALL'), ('category__isnull', True), ('subcategory__isnull', True), ('product__isnull', True), ('variant__isnull', True), ('brand__isnull', True), ('brand_normalized__isnull', True)), models.Q(('target_type', 'CATEGORY'), ('category__isnull', False), ('subcategory__isnull', True), ('product__isnull', True), ('variant__isnull', True), ('brand__isnull', True), ('brand_normalized__isnull', True)), models.Q(('target_type', 'SUBCATEGORY'), ('category__isnull', True), ('subcategory__isnull', False), ('product__isnull', True), ('variant__isnull', True), ('brand__isnull', True), ('brand_normalized__isnull', True)), models.Q(('target_type', 'BRAND'), ('category__isnull', True), ('subcategory__isnull', True), ('product__isnull', True), ('variant__isnull', True), ('brand__isnull', False), ('brand_normalized__isnull', False)), models.Q(('target_type', 'PRODUCT'), ('category__isnull', True), ('subcategory__isnull', True), ('product__isnull', False), ('variant__isnull', True), ('brand__isnull', True), ('brand_normalized__isnull', True)), models.Q(('target_type', 'VARIANT'), ('category__isnull', True), ('subcategory__isnull', True), ('product__isnull', True), ('variant__isnull', False), ('brand__isnull', True), ('brand_normalized__isnull', True)), _connector='OR'), name='promo_rule_target_consistency'), models.UniqueConstraint(condition=models.Q(('target_type', 'ALL')), fields=('promotion', 'target_type'), name='promo_rule_unique_all_target'), models.UniqueConstraint(condition=models.Q(('target_type', 'CATEGORY')), fields=('promotion', 'category'), name='promo_rule_unique_category_target'), models.UniqueConstraint(condition=models.Q(('target_type', 'SUBCATEGORY')), fields=('promotion', 'subcategory'), name='promo_rule_unique_subcategory_target'), models.UniqueConstraint(condition=models.Q(('target_type', 'BRAND')), fields=('promotion', 'brand_normalized'), name='promo_rule_unique_brand_target'), models.UniqueConstraint(condition=models.Q(('target_type', 'PRODUCT')), fields=('promotion', 'product'), name='promo_rule_unique_product_target'), models.UniqueConstraint(condition=models.Q(('target_type', 'VARIANT')), fields=('promotion', 'variant'), name='promo_rule_unique_variant_target')],
            },
        ),
    ]
