# Generated by Django 6.0.8 on 2026-09-05 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_otp_accounts_ot_identif_8b8de2_idx_and_more'),
        ('catalog', '0011_delivery_engine_schema'),
        ('orders', '0002_payment_payment_provider_order_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_path', models.CharField(blank=True, max_length=500)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=30)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Analytics Session',
                'verbose_name_plural': 'Analytics Sessions',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.category')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='accounts.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.subcategory')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='catalog.productvariant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.analyticssession')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
            },
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['customer', '-last_seen_at'], name='analytics_sess_customer_last'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['guest_id', '-last_seen_at'], name='analytics_sess_guest_last'),
        ),
        migrations.AddIndex(
            model_name='analyticssession',
            index=models.Index(fields=['-last_seen_at'], name='analytics_sess_last_seen'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_name', '-occurred_at'], name='analytics_evt_name_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['customer', '-occurred_at'], name='analytics_evt_customer_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session', '-occurred_at'], name='analytics_evt_session_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['guest_id', '-occurred_at'], name='analytics_evt_guest_time'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['product', 'event_name', '-occurred_at'], name='analytics_evt_product'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['variant', 'event_name', '-occurred_at'], name='analytics_evt_variant'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['order', '-occurred_at'], name='analytics_evt_order_time'),
        ),
    ]
