# Generated by Django 6.0.7 on 2026-07-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='catalogs/')),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('imported', 'Imported'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_imports', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rgd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mb_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('standard_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finish', models.CharField(blank=True, max_length=50)),
                ('finishes', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('collection', models.CharField(blank=True, max_length=120)),
                ('series', models.CharField(blank=True, max_length=120)),
                ('raw_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_products/')),
                ('is_imported', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('sku_confidence', models.FloatField(default=0.0)),
                ('name_confidence', models.FloatField(default=0.0)),
                ('price_confidence', models.FloatField(default=0.0)),
                ('layout_confidence', models.FloatField(default=0.0)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_products', to='catalog_import.catalogimport')),
            ],
            options={
                'ordering': ['catalog', 'page_number', 'sku'],
            },
        ),
    ]
