# Generated by Django 6.0.7 on 2026-07-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='parsedproduct',
            name='variant_axis_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parsedproduct',
            name='variant_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
