# Generated by Django 6.0.7 on 2026-07-30 14:50

import catalog_import.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_import', '0002_parsedproduct_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimport',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=catalog_import.storage.CatalogImportStorage(), upload_to=''),
        ),
    ]
