# Generated by Django 6.0.7 on 2026-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_import', '0003_alter_catalogimport_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedproduct',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
