# Generated by Django 6.0.7 on 2026-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_import', '0005_parsedproduct_variant_result_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedproduct',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
