# Generated by Django 6.0.7 on 2026-08-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_identif_8b8de2_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password')], default='register', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['identifier', 'channel', 'purpose', 'is_used'], name='accounts_ot_identif_0d77ff_idx'),
        ),
    ]
