# Generated by Django 6.0.8 on 2026-09-17 21:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otp_accounts_ot_identif_8b8de2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, help_text='Server-side reason for revocation, for example logout, password_reset, admin_revoke, revoke_all, or expired.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Customer Auth Session',
                'verbose_name_plural': 'Customer Auth Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('session_revoked', 'Session Revoked'), ('session_expired', 'Session Expired')], db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('identifier_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to='accounts.customer')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.customerauthsession')),
            ],
            options={
                'verbose_name': 'Customer Auth Event',
                'verbose_name_plural': 'Customer Auth Events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerauthsession',
            index=models.Index(fields=['customer', '-created_at'], name='accounts_cu_custome_cc0f09_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthsession',
            index=models.Index(fields=['customer', 'is_active'], name='accounts_cu_custome_f0fe0b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthsession',
            index=models.Index(fields=['session_id'], name='accounts_cu_session_629e17_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthsession',
            index=models.Index(fields=['expires_at', 'is_active'], name='accounts_cu_expires_b60676_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthevent',
            index=models.Index(fields=['customer', '-occurred_at'], name='accounts_cu_custome_78e346_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthevent',
            index=models.Index(fields=['customer', 'event_type', '-occurred_at'], name='accounts_cu_custome_ae4925_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthevent',
            index=models.Index(fields=['session', '-occurred_at'], name='accounts_cu_session_7e62f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauthevent',
            index=models.Index(fields=['identifier_hash', '-occurred_at'], name='accounts_cu_identif_2f9762_idx'),
        ),
    ]
