"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from datetime import timedelta
from pathlib import Path
import os

import cloudinary
import dj_database_url
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-key-change-in-production",
)

DEBUG = os.getenv("DEBUG", "False") == "True"

GEOAPIFY_API_KEY = os.getenv("GEOAPIFY_API_KEY")


def _env_list(name):
    return [
        value.strip()
        for value in os.getenv(name, "").split(",")
        if value.strip()
    ]


def _env_bool(name, default=False):
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS")


# ------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third Party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    # "silk",

    # Local
    "catalog",
    "catalog_import",
    "accounts",
    "cart",
    "cloudinary",
    "cloudinary_storage",
    "orders",
    "invoices",
    "promotions",
    "analytics",
]


# ------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------

MIDDLEWARE = [
    # "silk.middleware.SilkyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ------------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}


# ------------------------------------------------------------------
# PASSWORD VALIDATION
# ------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ------------------------------------------------------------------
# STATIC FILES
# ------------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# ------------------------------------------------------------------
# MEDIA FILES
# ------------------------------------------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# ------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ------------------------------------------------------------------
# CORS
# ------------------------------------------------------------------

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = _env_list("CORS_ALLOWED_ORIGINS")

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-guest-id",
    "idempotency-key",
    "x-client-timeout-ms",
    "x-analytics-session-id",
]


# ------------------------------------------------------------------
# CSRF
# ------------------------------------------------------------------

CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")


# ------------------------------------------------------------------
# SECURITY (Production)
# ------------------------------------------------------------------

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True


# ------------------------------------------------------------------
# CUSTOMER AUTH SESSION / SECURITY AUDIT
# ------------------------------------------------------------------

# Maximum lifetime of one server-side customer authentication session.
# This is the PostgreSQL auth-session lifetime, independent of analytics.
AUTH_SESSION_LIFETIME_SECONDS = int(
    os.getenv(
        "AUTH_SESSION_LIFETIME_SECONDS",
        str(60 * 60 * 24 * 30),
    )
)

# Avoid a database UPDATE on every authenticated request.
AUTH_SESSION_ACTIVITY_UPDATE_INTERVAL_SECONDS = int(
    os.getenv(
        "AUTH_SESSION_ACTIVITY_UPDATE_INTERVAL_SECONDS",
        "60",
    )
)

# Used only for the customer-facing "online" indicator.
AUTH_SESSION_ONLINE_WINDOW_SECONDS = int(
    os.getenv(
        "AUTH_SESSION_ONLINE_WINDOW_SECONDS",
        "300",
    )
)

# Maximum serialized metadata retained in one auth audit event.
AUTH_AUDIT_MAX_METADATA_BYTES = int(
    os.getenv(
        "AUTH_AUDIT_MAX_METADATA_BYTES",
        str(16 * 1024),
    )
)

# X-Forwarded-For / Forwarded headers are NEVER trusted by default.
# Enable only when the reverse-proxy source network is explicitly listed.
AUTH_TRUST_PROXY_HEADERS = _env_bool(
    "AUTH_TRUST_PROXY_HEADERS",
    default=False,
)

AUTH_TRUSTED_PROXY_CIDRS = _env_list(
    "AUTH_TRUSTED_PROXY_CIDRS",
)


# ------------------------------------------------------------------
# DJANGO REST FRAMEWORK
# ------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.services.AppJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination"
    ),
    "PAGE_SIZE": 20,
}


# ------------------------------------------------------------------
# SIMPLE JWT
# ------------------------------------------------------------------

# Existing customer/staff token behavior is retained:
#   access  = 8 hours
#   refresh = 7 days
#
# Customer JWTs additionally carry auth_session_id in accounts.services.py.
# Server-side CustomerAuthSession remains authoritative for customer access.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# ------------------------------------------------------------------
# DRF SPECTACULAR
# ------------------------------------------------------------------

SPECTACULAR_SETTINGS = {
    "TITLE": "BlazeLine API",
    "DESCRIPTION": "BlazeLine Building Materials Platform API",
    "VERSION": "1.0.0",
}


# ------------------------------------------------------------------
# EMAIL OTP + PHONE OTP (accounts app)
# ------------------------------------------------------------------

if DEBUG and not os.getenv("EMAIL_HOST_USER"):
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.hostinger.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True") == "True"
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "BlazeLine <no-reply@blazeline.in>",
)

MSG91_AUTH_KEY = os.getenv("MSG91_AUTH_KEY")
MSG91_OTP_TEMPLATE_ID = os.getenv("MSG91_OTP_TEMPLATE_ID")
MSG91_WHATSAPP_INTEGRATED_NUMBER = os.getenv(
    "MSG91_WHATSAPP_INTEGRATED_NUMBER"
)
MSG91_WHATSAPP_TEMPLATE_NAME = os.getenv(
    "MSG91_WHATSAPP_TEMPLATE_NAME",
    "otp_verification",
)
MSG91_WHATSAPP_TEMPLATE_LANGUAGE = os.getenv(
    "MSG91_WHATSAPP_TEMPLATE_LANGUAGE",
    "en",
)
