# Generated by Django 6.0.7 on 2026-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceablePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Kolkata', max_length=100)),
                ('state', models.CharField(default='West Bengal', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviceable Pincode',
                'verbose_name_plural': 'Serviceable Pincodes',
                'ordering': ['pincode'],
            },
        ),
    ]
