# Generated by Django 6.0.7 on 2026-07-29 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_serviceablepincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('project_location', models.CharField(max_length=255)),
                ('delivery_pincode', models.CharField(max_length=6)),
                ('project_type', models.CharField(max_length=80)),
                ('materials', models.JSONField(default=list)),
                ('requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quote_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='catalog.quoterequest')),
            ],
            options={
                'verbose_name': 'Quote Attachment',
                'verbose_name_plural': 'Quote Attachments',
                'ordering': ['id'],
            },
        ),
    ]
