# Generated by Django 6.0.7 on 2026-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_quoterequest_quoteattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(),
        ),
    ]
