# Generated by Django 6.0.7 on 2026-08-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_subcategory_options_subcategory_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_config', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Homepage Category',
                'verbose_name_plural': 'Homepage Categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
