# Generated by Django 6.0.7 on 2026-08-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text="Used only as a tie-breaker when a pincode's zone alone doesn't disambiguate rules.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Higher value = evaluated first when specificity ties.')),
                ('pricing_mode', models.CharField(choices=[('fixed', 'Fixed Amount'), ('per_item', 'Per Item'), ('per_unit', 'Per Unit'), ('per_kg', 'Per Kg'), ('percentage', 'Percentage'), ('free', 'Free Delivery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Used only when pricing_mode = percentage.', max_digits=5, null=True)),
                ('stack_mode', models.CharField(choices=[('override', 'Override — replaces lower-priority charge'), ('add', 'Add — stacks on top of other matched rules'), ('stop', 'Stop — apply and stop evaluating further rules')], default='add', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='catalog.product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='catalog.subcategory')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='catalog.productvariant')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalog.deliveryzone')),
            ],
            options={
                'verbose_name': 'Delivery Rule',
                'verbose_name_plural': 'Delivery Rules',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('base_charge', 'Base Charge'), ('surcharge', 'Surcharge'), ('discount', 'Discount'), ('free_delivery', 'Free Delivery')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('label', models.CharField(blank=True, help_text="Customer-facing breakdown label, e.g. 'Heavy Shipment Fee'.", max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='catalog.deliveryrule')),
            ],
            options={
                'verbose_name': 'Delivery Rule Action',
                'verbose_name_plural': 'Delivery Rule Actions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('cart_value', 'Cart Value'), ('weight', 'Total Weight (kg)'), ('quantity', 'Item Quantity'), ('total_quantity', 'Total Cart Quantity'), ('customer_type', 'Customer Type'), ('shipping_type', 'Shipping Type')], max_length=50)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '='), ('in', 'in')], max_length=10)),
                ('value', models.CharField(help_text='Stored as string; cast to correct type by the evaluator at runtime.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='catalog.deliveryrule')),
            ],
            options={
                'verbose_name': 'Delivery Rule Condition',
                'verbose_name_plural': 'Delivery Rule Conditions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='serviceablepincode',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Optional — assign for zone-based delivery rules. Leave blank to keep legacy Kolkata-only behavior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincodes', to='catalog.deliveryzone'),
        ),
        migrations.AddIndex(
            model_name='deliveryrule',
            index=models.Index(fields=['active', 'priority'], name='catalog_del_active_199413_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrule',
            index=models.Index(fields=['zone', 'category', 'subcategory', 'product', 'variant'], name='catalog_del_zone_id_38f15f_idx'),
        ),
    ]
