# Generated by Django 6.0.7 on 2026-08-27 14:56

from django.db import migrations


def reset_legacy_delivery_rules(apps, schema_editor):
    """
    Fresh-start migration for the delivery engine.

    Remove legacy DeliveryRule configuration before the schema
    transition. The new delivery engine stores pricing in
    DeliveryRuleAction, so legacy DeliveryRule rows are intentionally
    not carried forward.
    """
    DeliveryRule = apps.get_model(
        "catalog",
        "DeliveryRule",
    )

    DeliveryRule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_delivery_engine"),
    ]

    operations = [
        migrations.RunPython(
            reset_legacy_delivery_rules,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
