# Generated by Django 6.0.7 on 2026-08-27 14:56

import django.core.validators

from django.db import migrations, models


def reset_legacy_delivery_rules(apps, schema_editor):
    """
    Fresh-start migration for the delivery engine.

    The previous delivery-rule schema stored pricing directly on
    DeliveryRule. The new production architecture stores pricing
    inside DeliveryRuleAction.

    We intentionally start the new delivery system with no legacy
    delivery rules, because the legacy configuration is not being
    carried forward.
    """
    DeliveryRule = apps.get_model(
        "catalog",
        "DeliveryRule",
    )

    DeliveryRule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_delivery_engine"),
    ]

    operations = [
        # ----------------------------------------------------------
        # FRESH DELIVERY START
        # ----------------------------------------------------------

        migrations.RunPython(
            reset_legacy_delivery_rules,
            reverse_code=migrations.RunPython.noop,
        ),

        # ----------------------------------------------------------
        # DELIVERY ZONE
        # ----------------------------------------------------------

        migrations.AlterModelOptions(
            name="deliveryzone",
            options={
                "ordering": ["-priority", "name"],
                "verbose_name": "Delivery Zone",
                "verbose_name_plural": "Delivery Zones",
            },
        ),

        # ----------------------------------------------------------
        # REMOVE LEGACY DELIVERY RULE PRICING
        # ----------------------------------------------------------

        migrations.RemoveField(
            model_name="deliveryrule",
            name="amount",
        ),

        migrations.RemoveField(
            model_name="deliveryrule",
            name="percentage",
        ),

        migrations.RemoveField(
            model_name="deliveryrule",
            name="pricing_mode",
        ),

        migrations.RemoveField(
            model_name="deliveryrule",
            name="stack_mode",
        ),

        # ----------------------------------------------------------
        # NEW DELIVERY RULE CONTROLS
        # ----------------------------------------------------------

        migrations.AddField(
            model_name="deliveryrule",
            name="combine_mode",
            field=models.CharField(
                choices=[
                    (
                        "add",
                        "Add — stack on top of the running total so far",
                    ),
                    (
                        "override",
                        "Override — discard the running total, "
                        "restart from this rule",
                    ),
                ],
                default="add",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="deliveryrule",
            name="stop_after",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Stop evaluating any further "
                    "(more specific / higher-priority) rules "
                    "once this one is applied."
                ),
            ),
        ),

        # ----------------------------------------------------------
        # DELIVERY RULE ACTION PRICING
        # ----------------------------------------------------------

        migrations.AddField(
            model_name="deliveryruleaction",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount"),
                    ("per_item", "Per Item"),
                    ("per_unit", "Per Unit"),
                    ("per_kg", "Per Kg"),
                    (
                        "percentage",
                        "Percentage (of this rule's scope subtotal)",
                    ),
                ],
                default="fixed",
                help_text=(
                    "Ignored when action_type = Free Delivery."
                ),
                max_length=20,
            ),
        ),

        # ----------------------------------------------------------
        # PRIORITY
        # ----------------------------------------------------------

        migrations.AlterField(
            model_name="deliveryrule",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text=(
                    "Tie-breaker within the same specificity level. "
                    "Rules are evaluated from broadest to most specific, "
                    "and within equal specificity, from lowest to highest "
                    "priority — so a higher priority rule is evaluated "
                    "later and takes precedence."
                ),
            ),
        ),

        migrations.AlterField(
            model_name="deliveryruleaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text=(
                    "Amount, or percent value (e.g. 5 = 5%) when "
                    "pricing_mode = Percentage. Must be non-negative — "
                    "sign is inferred from action_type."
                ),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),

        migrations.AlterField(
            model_name="deliveryzone",
            name="priority",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "Higher number = higher priority. Currently NOT "
                    "consumed by the evaluator (each pincode maps to "
                    "exactly one zone via a ForeignKey, so there is no "
                    "ambiguity to break). Reserved for future "
                    "overlapping-zone support."
                ),
            ),
        ),
    ]
