# Generated by Django 6.0.8 on 2026-09-18 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerauthsession_customerauthevent_and_more'),
        ('catalog', '0011_delivery_engine_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('property_type', models.CharField(max_length=100)),
                ('service_required', models.CharField(max_length=150)),
                ('property_size', models.CharField(max_length=100)),
                ('project_stage', models.CharField(max_length=100)),
                ('estimated_budget', models.CharField(max_length=100)),
                ('timeline', models.CharField(max_length=100)),
                ('design_preference', models.CharField(max_length=100)),
                ('inspiration_photo', models.ImageField(blank=True, null=True, upload_to='interior_consultations/')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('property_location', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('preferred_consultation_date', models.DateField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('additional_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contact_pending', 'Contact Pending'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=30)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior Consultation',
                'verbose_name_plural': 'Interior Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteriorConsultationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('rescheduled', 'Rescheduled'), ('internal_note', 'Internal Note'), ('follow_up_set', 'Follow-up Set'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('converted', 'Converted')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Interior Consultation Activity',
                'verbose_name_plural': 'Interior Consultation Activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('internal_note', 'Internal Note'), ('follow_up_set', 'Follow-up Set'), ('contacted', 'Contacted'), ('quote_sent', 'Quote Sent'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Quote Request Activity',
                'verbose_name_plural': 'Quote Request Activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='requested_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='source',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='source_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['assigned_to', 'status'], name='catalog_quo_assigne_3163ba_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['next_follow_up_at'], name='catalog_quo_next_fo_f39273_idx'),
        ),
        migrations.AddField(
            model_name='interiorconsultation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interior_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interiorconsultation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_consultations', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='interiorconsultationactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_consultation_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interiorconsultationactivity',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='catalog.interiorconsultation'),
        ),
        migrations.AddField(
            model_name='quoterequestactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_request_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequestactivity',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='catalog.quoterequest'),
        ),
        migrations.AddIndex(
            model_name='interiorconsultation',
            index=models.Index(fields=['status', '-created_at'], name='catalog_int_status_9c1ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='interiorconsultation',
            index=models.Index(fields=['assigned_to', 'status'], name='catalog_int_assigne_8c60ed_idx'),
        ),
        migrations.AddIndex(
            model_name='interiorconsultation',
            index=models.Index(fields=['next_follow_up_at'], name='catalog_int_next_fo_32e0da_idx'),
        ),
        migrations.AddIndex(
            model_name='interiorconsultation',
            index=models.Index(fields=['pincode'], name='catalog_int_pincode_188ae4_idx'),
        ),
    ]
