# Generated by Django 6.0.8 on 2026-09-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_interiorconsultation_interiorconsultationactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrated_number', models.CharField(db_index=True, help_text='MSG91 integrated WhatsApp business number.', max_length=20)),
                ('customer_number', models.CharField(help_text='Customer WhatsApp number.', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=500)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, help_text='WhatsApp customer-service session expiry time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
                'verbose_name_plural': 'WhatsApp Conversations',
                'ordering': ['-last_message_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-last_message_at'], name='wa_conv_status_last_msg'), models.Index(fields=['integrated_number', 'customer_number'], name='wa_conv_numbers')],
                'constraints': [models.UniqueConstraint(fields=('integrated_number', 'customer_number'), name='uniq_whatsapp_conversation_number')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=20)),
                ('message_type', models.CharField(default='text', help_text='text, image, document, audio, video, etc.', max_length=30)),
                ('text', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, help_text='WhatsApp/MSG91 message ID (WAMID/UUID where available).', max_length=255, null=True, unique=True)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='catalog.whatsappconversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'occurred_at'], name='wa_msg_conv_occurred'), models.Index(fields=['direction', 'occurred_at'], name='wa_msg_direction_time')],
            },
        ),
    ]
