# Generated by Django 6.0.8 on 2026-09-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Cart Item Idempotency Key',
                'verbose_name_plural': 'Cart Item Idempotency Keys',
                'indexes': [models.Index(fields=['created_at'], name='cart_idem_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('cart', 'key'), name='uniq_cart_idempotency_key')],
            },
        ),
    ]
