# Generated by Django 6.0.8 on 2026-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_payment_provider_order_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable checkout-time snapshot of promotions applied to this order.'),
        ),
    ]
