# Generated by Django 6.0.8 on 2026-10-01 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_promotion_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('storefront', 'Storefront'), ('direct', 'Direct Order')], db_index=True, default='storefront', help_text='How the order was created.', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('cod', 'Cash on Delivery'), ('credit', 'Credit Terms'), ('payment_link', 'Payment Link')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='razorpay', max_length=50)),
                ('provider_link_id', models.CharField(db_index=True, help_text='Razorpay Payment Link ID.', max_length=255, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='BlazeLine-side reference used while creating the link.', max_length=255)),
                ('short_url', models.URLField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='created', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Non-secret Razorpay response/event metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='orders.payment')),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='paylink_payment_created_idx'), models.Index(fields=['status', '-created_at'], name='paylink_status_created_idx')],
            },
        ),
    ]
